### ISSUE TITLE
Downpour SGD Model Parallelism?

### ISSUE THREAD

**Issue by johnxqiu** [vlimant/mpi_learn#14]
When reading the Dean et al paper, it seems like downpour SGD is an implementation of model parallelism. Is this actually implemented in this library?

**Comment by duanders** [comment]
Hi, sorry for the late reply.  

Model parallelism is a major focus of the Dean et al paper, but the Downpour algorithm is introduced there as a method for data parallelism.  In `mpi_learn` you could achieve model parallelism (if using the tensorflow backend to keras) by creating a custom `ModelBuilder` class that allocates model layers on multiple devices.  You can look at the `ModelFromJsonTF` class for an example of placing layers on a particular device.  It might require a small modification to the `MPIDriver.py` driver script to deal with the logic of giving N GPUs to each worker process.  

Unfortunately `mpi_learn` doesn't provide any way to run a sharded parameter server as is done in the Dean et al implementation.  The updating of model weights is handled by a single MPI process.

**Comment by johnxqiu** [comment]
thanks for the clarification!

**Comment by anupamme** [comment]
@qiubs did you manage to implement downpour SGD in mpi_learn?

I am also at a point where I have to implement this so thought I could learn from your experience.
