### ISSUE TITLE
invalid model

### ISSUE THREAD

**Issue by vlimant** [vlimant/mpi_learn#27]
while coupled with mpi-opt, the model_builder could fail and this hangs the whole process any further.
I wonder how we can most efficiently catch this and fail-safe

**Comment by vloncar** [comment]
The model building can fail in two places:
1) In mpi_learn, during `compile_model()`. This assumes that the model json file is invalid
2) In mpi_opt, during creation of the model in `test_*` functions of `mpiLAPI.py`.

Fixing 2) would be enough. Do we need 1) as well?

**Comment by vlimant** [comment]
with #26 mpiLAPI is not going to be relevant.
not sure how to propagate the None model from 2) down to mpi-opt fom

**Comment by vloncar** [comment]
We would need to change the propagation logic somewhat, as `None` model_builder is interpreted as the end of optimization process. Once refactored, we can detect `None` as invalid model, and set FoM to some nonsense value (e.g., `sys.float_info.max`)

**Comment by vlimant** [comment]
only relevant for mpi-opt https://github.com/vlimant/mpi_opt/pull/18
